### ISSUE TITLE
Add realized P/L value and % in the second table with totals

### ISSUE THREAD

**Issue by antonrd** [antonrd/investment-portfolio-viewer#1]
The table in the screenshot only shows unrealized P/L and weighted P/L. It would be nice to add total realized P/L columns to the table. This will be two columns: for the actual value and the % P/L.
![screen shot 2017-01-31 at 19 21 52](https://cloud.githubusercontent.com/assets/236158/22476324/99faef84-e7ea-11e6-80ee-db3755406aa9.png)

**Comment by dimitrovmaksim** [comment]
Done!
